spring.application.name=BTS_Backend
spring.datasource.url=jdbc:mysql://localhost:3306/music_db  # ??m b?o tên c? s? d? li?u ?úng
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=aggF+q3XsW6NstgDqcUrZrtW+Cexgunh5SZGhe/BiHYVvHN4LJiNV7kl23Hjo0jH
jwt.expiration=3600000  
jwt.refresh-expiration=86400000

spring.web.resources.static-locations=file:///C:/Users/bdtcl/Desktop/Flutter/music/
server.address=0.0.0.0
server.port=8080

